[package]
name = "ascii-based-filter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "asbf"
path = "src/main.rs"

[dependencies]
image = "0.25.6"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
